<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title><?php print $page_title ?? 'Application'; ?></title>
    <link href='//fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    <style>
        body {
            margin: 50px 0 0 0;
            padding: 0;
            width: 100%;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-align: center;
            color: #aaa;
            font-size: 18px;
        }

        h1 {
            color: #0055aa;
            letter-spacing: -10px;
            font-family: 'Open Sans', sans-serif;
            font-size: 10rem;
            font-weight: 200;
            margin-bottom: 0;
        }
    </style>
</head>
    <body>
        <?php
            $layout = $data['layout'] ?? 'index';
            include $layout.'.phtml';
        ?>
    </body>
</html>
